package dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import dao.SensorMessage;
import dao.User;
import dao.MessageDestination;

import dao.SensorMessageDao;
import dao.UserDao;
import dao.MessageDestinationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sensorMessageDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig messageDestinationDaoConfig;

    private final SensorMessageDao sensorMessageDao;
    private final UserDao userDao;
    private final MessageDestinationDao messageDestinationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sensorMessageDaoConfig = daoConfigMap.get(SensorMessageDao.class).clone();
        sensorMessageDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        messageDestinationDaoConfig = daoConfigMap.get(MessageDestinationDao.class).clone();
        messageDestinationDaoConfig.initIdentityScope(type);

        sensorMessageDao = new SensorMessageDao(sensorMessageDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        messageDestinationDao = new MessageDestinationDao(messageDestinationDaoConfig, this);

        registerDao(SensorMessage.class, sensorMessageDao);
        registerDao(User.class, userDao);
        registerDao(MessageDestination.class, messageDestinationDao);
    }
    
    public void clear() {
        sensorMessageDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        messageDestinationDaoConfig.getIdentityScope().clear();
    }

    public SensorMessageDao getSensorMessageDao() {
        return sensorMessageDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MessageDestinationDao getMessageDestinationDao() {
        return messageDestinationDao;
    }

}
