package dao;

import   requestresponse.ExcludeFromGson;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    /** Not-null value. */
     @SerializedName("uuid_user")
    private String uuid_user;
     @SerializedName("user_id")
    private String user_id;
     @SerializedName("password")
    private String password;
     @SerializedName("token")
    private String token;

    public User() {
    }

    public User(String uuid_user) {
        this.uuid_user = uuid_user;
    }

    public User(String uuid_user, String user_id, String password, String token) {
        this.uuid_user = uuid_user;
        this.user_id = user_id;
        this.password = password;
        this.token = token;
    }

    /** Not-null value. */
    public String getUuid_user() {
        return uuid_user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid_user(String uuid_user) {
        this.uuid_user = uuid_user;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

}
